<?php
/** @var \Magento\Framework\Escaper $escaper */
?>
<div id="meee">
    <div id="econt-iframe-modal">
        <div id="place_iframe_here" class="content"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Oxl_Delivery/js/view/cms-block": {
                "AjaxUrl": "<?= $escaper->escapeHtml($block->getAjaxUrl()); ?>"
            }
        }
    }
</script>

<style>
    #place_iframe_here {
        padding-top: 25px;
    }
    
    #place_iframe_here > iframe {
        width: 100%;
        min-height: 500px;
        border: none;
        height: 700px;
        overflow: hidden
    }

    .modal-content {
        font-size: 16px;
    }
</style>
