<?php /** @var $block \Oxl\Delivery\Block\Adminhtml\Order\AbstractOrder */ ?>
<?php /** @var $escaper \Magento\Framework\Escaper */ ?>
<?php
$order = $block->getOrder();
$popupUrl = $block->helper(\Oxl\Delivery\Helper\Data::class)->getTrackingPopupUrl($order);
?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $escaper->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()): ?>
            <?php if ($order->getShippingMethod() === 'econtdelivery_econtdelivery'): ?>
                <p>
                    <a href="#" id="linkId" onclick="popWin(
                    '<?= $escaper->escapeHtml($popupUrl) ?>',
                    'trackshipment',
                        'width=800,height=600,resizable=yes,scrollbars=yes')"
                    title="<?= $escaper->escapeHtml(__('Track Order')) ?>">
                        <?= $escaper->escapeHtml(__('Track Order')) ?>
                    </a>
                </p>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $escaper->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($block->helper(Magento\Tax\Helper\Data::class)->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= $escaper->escapeHtml($_excl); ?>
            <?php if ($block->helper(Magento\Tax\Helper\Data::class)->displayShippingBothPrices()
                && $_incl != $_excl): ?>
                (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= $escaper->escapeHtml($_incl) ?>)
            <?php endif; ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
</div>
