<?php
/** @var \Magento\Shipping\Block\Adminhtml\View $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Sales\Model\Order $order */
$order = $block->getOrder();
?>
<div class="dashboard-advanced-reports-actions">
    <button id="oxl-tracking-status" type="button" class="action action-advanced-reports" 
        data-index="analytics-service-link" 
        title="Generate Waybill" 
        onclick="popWin('<?= $block->escapeUrl($this->helper(\Oxl\Delivery\Helper\Data::class)->getWaybillPopupUrl($order->getId())); ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')"
        data-ui-id="oxl-tracking-status">
        <span><?= $block->escapeHtml(__('Print')); ?></span>
    </button>
</div>